config/routes.rb
Todo::Application.routes.draw do
  resources :tasks

  root :to =>'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :name, :notes, :status, :order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def user_session
  	@user_session ||= UserSession.new(session)
  end
	helper_method :user_session
  #session[:user_id] = @current_user.id
  #User.find(session[:user_id])
  #session[:user] = @user
  #
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # def initialize(session)
  #   @session = session
  # end

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    session[:user_name] = "Erin" 
    session[:user_id] = @usser_session

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])
    
    (session[:tasks_viewed] ||= []).unshift(Task.find(params[:id]))
    #session[:tasks_viewed] = []
    session[:tasks_viewed].uniq;
    if  session[:tasks_viewed].length > 5
      session[:tasks_viewed].pop;
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>todo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>
</head>
<body>
	<div id="TopNav">
		<div class="navbar">
		  <div class="navbar-inner">
		    <a class="brand" href="/">List</a>
		    <ul class="nav">
		       <li ><a href="/tasks/new">Add</a></li>
		    </ul>
		    <div class="TopNavId">Welcome <%=session[:user_name]%><span class="icon-user"></span></div>
		  </div>
		</div>
	</div>
	<div id="MainCenter">
		<%= yield %>
	</div>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field control-group">
    <%= f.label :name, :id => 'namelabel' %>
    <%= f.text_field :name, :class => 'required' %>
  </div>
  <div class="field">
    <%= f.label :notes %>
    <%= f.text_field :notes %>
  </div>

  <div class="field required">
    <%= f.label :status %><br />
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit 'Add it', :class => 'btn btn-primary submit' %>
  </div>
  <script>jQuery('.submit').click(function(e){
    //alert(AUTH_TOKEN);
        if (jQuery('#task_name').val() == '') {
          e.preventDefault();
          jQuery( '#task_name').parent().addClass( 'error' );
          jQuery( '#namelabel' ).text( 'Name required' );
          jQuery( this ).parent().children( '.ajax-feedback' ).fadeIn();
        }else{
          // task = new Object();
          // task['notes'] = encodeURIComponent(jQuery('#task_notes').val());
          // task['name'] = encodeURIComponent(jQuery('#task_name').val());
          // task['status']= encodeURIComponent(jQuery('#task_status').val());
          // //$.post("/tasks", { task[name]: jQuery('#task_name').val(), task[notes]: jQuery('#task_notes').val(), task[status]: jQuery('#task_status').val(), commit: 'Add it') } );
          // $.post("/tasks", { utf8: '✓', tasks:  task, authenticity_token: encodeURIComponent(AUTH_TOKEN),  commit:  'Add it'},
          //   function(data) {
          //     //alert("success");
          //     window.location = "/";
          //   }
          // );
        }
  });</script>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div id="mainMarq"></div>

<table class="tasksHomeList">
  <tr>
    <th><span class="text-info">Task</span></th>
    <!--<th>Notes</th>-->
    <th><span class="muted">Status </span></th>
    <th></th>
    <th><span class="muted">Actions</span></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><strong><%= task.name %></strong></td>
    <!--<td><%= task.notes %></td>-->
    <td>
      <% if task.status == true %>
        <span class="icon-ok"></span>
        <% else %>
          <span class="icon-minus"></span>
        <% end %>
    </td>
    <td><%= link_to 'Info', task , :class=> ''%></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Remove', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<!--<%= link_to 'New Task', new_task_path, :class => 'btn-primary' %>-->

<script>

var list = ['What if the world had more then lists?', 'What if it had Todos?', 'like a big list of ToDos?', 'Really, I mean like allot of ToDos!', 'We apologize, those that have written the Marquee have been sacked.'];  // list of blurbs

var txt = $('#mainMarq');  // The container in which to render the list

var options = {
  duration: 1000,          // Time (ms) each blurb will remain on screen
  rearrangeDuration: 1000, // Time (ms) a character takes to reach its position
  effect: 'random',        // Animation effect the characters use to appear
  centered: true           // Centers the text relative to its container
}

txt.textualizer(list, options); // textualize it!
txt.textualizer('start'); // start


</script>

app/views/tasks/new.html.erb
<h2>Add a task</h2>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h3><span class="text-info">Task </span><%= @task.name %></h3>
<p id="notice"><%= notice %></p>
<div class="taskMoreInfo">
	<p>
	  <b>Notes:</b>
	  <%= @task.notes %>
	</p>

	<p>
	  <b>Status:</b>
	   <% if @task.status == true %>
	        <span class="icon-ok"></span>
	    <% else %>
	    	<span class="icon-minus"></span> Not Done
	    <% end %>
	</p>
	
	<%= link_to 'Edit', edit_task_path(@task), :class => 'btn btn-primary submit'  %>
</div>

<div id="RecentTasks">
	<h3 ><span class="text-success"> Recent</span> Tasks</h3>

	 <table class="recentTasksViewed">
	 	<tr>
		    <th><span class="muted">Task</span></th>
		    <!--<th>Notes</th>-->
		    <th><span class="muted">Status</span></th>
		    <th></th>
		    <th></th>
		    <th></th>
	  	</tr>
	   <% session[:tasks_viewed].take(5).each do |task| %>
	    <tr>
	      <td><strong><%= task.name %></strong></td>
	      <!--<td><%= task.notes %></td>-->
	      <td>
	      	<% if task.status == true %>
        		<span class="icon-ok"></span>
        	<% else %>
          		<span class="icon-minus"></span>
        	<% end %>
	      </td>
	      <td><%= link_to 'Show', task %></td>
	    </tr>
	   <% end %>
	 </table>
</div>